version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    env_file: .env  # Load variables from .env
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - my_network

  airflow-webserver:
    image: apache/airflow:latest
    container_name: airflow-webserver
    env_file: .env  # Share the same .env variables
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - db
      - airflow-scheduler
    command: >
      bash -c "airflow db init && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:latest
    container_name: airflow-scheduler
    env_file: .env  # Share the same .env variables
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - my_network
    depends_on:
      - db
    command: >
      bash -c "airflow db init && airflow scheduler"

volumes:
  my_postgres_data:

networks:
  my_network:
    external: true